### PR TITLE
adding scale_x_cont + changing the first graph

### PR DESCRIPTION
**Pull request by heatherli12**

### CODE REVIEW

**Comment by davidkane9** [comment]
Can you remove the ds store object?

**Comment by heatherli12** [comment]
I'm not entirely sure how to do that, how do I remove it?

Many thanks,
Heather Li (she/they)

**Comment by davidkane9** [comment]
Delete it, commit and push.

**Comment by heatherli12** [comment]
I'm pretty sure I deleted it? It's not in the main page or anything, but for some reason it's not giving me changes to commit. 
Capture d’écran, le 2021-08-22 à 22 48 52

**Pull request merged**
