### PR TITLE
Added more comments to chapter 2

### PR DESCRIPTION
**Pull request by AM-lmn**
Wasn't able to get a whole lot of work done these past few days because of other commitments. For whatever reason, the git tab on my Rstudio said that I was ahead by 52 commits and I'm not sure how or why, but hopefully this doesn't create any significant problems.

Also updated the `renv.lock` file because I happened to open the chapter 6 file out of curiosity and it started yelling at me about that.

### CODE REVIEW

**Comment by davidkane9** [comment]
Remove your renv lock changes from this PR

**Comment by AM-lmn** [comment]
how do i do that

**Comment by davidkane9** [comment]
Read the set up guide again

Google

Nuke from orbit

**Comment by AM-lmn** [comment]
gonna try nuke from orbit

**Comment by davidkane9** [comment]
Often the best approach

**Comment by AM-lmn** [comment]
https://github.blog/changelog/2018-07-31-removing-files-from-a-pull-request/

you should be able to delete it yourself since you have write permissions im pretty sure

**Comment by davidkane9** [comment]
Did not work. Nuke from orbit and try again. Read links from Set Up about renv.

**Pull request closed without merging**
