### PR TITLE
Chapter 4

### PR DESCRIPTION
**Pull request by miriamheiss**

### CODE REVIEW

**Comment by davidkane9** [comment]
Don't add ds store files

**Comment by davidkane9** [comment]
Also, should you be committing changes in .r profile?

**Comment by miriamheiss** [comment]
Oh, I didn’t mean to commit that, thought I unchecked the box. I commented
something out, and meant to undo it, but forgot to

**Comment by miriamheiss** [comment]
Also, I don’t remember committing ds store files

**Pull request merged**
