### PR TITLE
Formidable

### PR DESCRIPTION
**Pull request by libryan261**

### CODE REVIEW

**Comment by libryan261** [comment]
Idk what the .iCloud ones are but this is just a test

**Comment by davidkane9** [comment]
Why are you changing 11 files?

**Comment by libryan261** [comment]
I just committed everything that was in the Git section. I didn't change anything in the actual files. They were just there when I first loaded in everything

**Comment by davidkane9** [comment]
Burn it all down and start again.

**Comment by libryan261** [comment]
Burn what down? the pull request thing?

**Comment by davidkane9** [comment]
Never mind.

**Comment by libryan261** [comment]
Hey Preceptor,

I just got a new computer. So I'm going to nuke it from orbit and start
again. I haven't worked on the wrangling tutorial so it wont affect
anything.

**Comment by davidkane9** [comment]
Good

**Pull request closed without merging**
