### PR TITLE
Updated getting started section

### PR DESCRIPTION
**Pull request by AtillaColak**

### CODE REVIEW

**Comment by davidkane9** [comment]
Code like this won't work on my machine:

use_python("C:\\Users\\KINGLE~1\\AppData\\Local\\Programs\\Python\\Python38\\python.exe")

Need to make the code generic, with no refererences to your paths.

**Comment by AtillaColak** [comment]
Got it. I'll fix it right away!

**Comment by AtillaColak** [comment]
Preceptor, I've edited the code and included the condition such that the code would be producible in every machine.

**Comment by davidkane9** [comment]
The plan is NOT to use Jupiter notebooks. Instead, we will do everything in Rmd files within RStudio.

**Comment by AtillaColak** [comment]
But in that case, wouldn't the python section be unnecessary in the first place?

**Comment by davidkane9** [comment]
Closing per discussion this morning

**Pull request closed without merging**
